query GET_SVRS {
  svrs {
    id
    name
    address
    photo_list {
      photo_id {
        id
      }
      type
    }
    program_list {
      id
      name
      description
      # age_from
      # age_to
      program_type_id {
        # id
        name
        photo_id {
          id
        }
      }
      date_list {
        # id
        date_start
        date_finish
        cost
        # services
        # social_certificate
        # cashback
        # payment_types {
        #   payment_types_id {
        #     id
        #     name
        #   }
        # }
      }
    }
    published
  }
}
